### ISSUE TITLE
バリデーション見直し

### ISSUE THREAD

**Issue by yunayuna** [4geru/2018-newbies#37]
- マイナス入れられるととか
- 小数点
- メールアドレス
- password

**Comment by 4geru** [comment]
passwordをする

**Comment by yakkun** [comment]
- [x] こういうの
- [ ] 使うと
- [x] 便利やで

**Comment by 4geru** [comment]
- [ ] 送金
- [x] パスワード
- [ ] クレジットカード

**Comment by yunayuna** [comment]
https://github.com/4geru/2018-newbies/pull/121
