### ISSUE TITLE
ユーザーが意図せずチャージできる問題

### ISSUE THREAD

**Issue by 4geru** [4geru/2018-newbies#86]
認証するボタン連打に耐える

多くのユーザーに使われた場合有効
サーバー側・フロント側の実装が必要
フロント disable

![2018-05-10 18 13 36](https://user-images.githubusercontent.com/8898432/39862161-e73181c2-547d-11e8-928e-b56bc845b540.png)

**Comment by yakkun** [comment]
んん？詳しくおせーてほしい。

**Comment by 4geru** [comment]
割とディスカッションの余地ありです...

**Comment by 4geru** [comment]
https://github.com/4geru/2018-newbies/pull/107 done
