### ISSUE TITLE
クレジットカードが変更された時にUIが変わらない

### ISSUE THREAD

**Issue by 4geru** [4geru/2018-newbies#91]

**Comment by 4geru** [comment]
![image](https://user-images.githubusercontent.com/8898432/39903564-b7bc456c-550e-11e8-9ab6-cb0e8b8b81e8.png)
こんな感じ？

**Comment by yunayuna** [comment]
良さそう！！

**Comment by 4geru** [comment]
https://github.com/4geru/2018-newbies/pull/95 done
