### ISSUE TITLE
CreditCard.create!とuser.create_credit_card!の違いを調べる

### ISSUE THREAD

**Issue by 4geru** [4geru/2018-newbies#92]
user.create_credit_cardじゃなくてCreditCard.createなのか問題
```
...
  def create
    current_user.credit_card.try(:destroy)
-    @credit_card = CreditCard.create!(credit_card_params.merge(user: current_user))
+    current_user.create_credit_card!(credit_card_params)

    render json: @credit_card.as_json(except: %i[stripe_id]), status: :created
  end
...
```
https://github.com/4geru/2018-newbies/blob/master/nova/app/controllers/api/credit_cards_controller.rb#L10

https://github.com/tnandate/2018-newbies/issues/37

**Comment by yakkun** [comment]
https://github.com/4geru/2018-newbies/blob/bc396418305918673066a785a1788af473cb8e06/nova/app/controllers/api/credit_cards_controller.rb#L10

**Comment by 4geru** [comment]
associationが繋がっているかの問題っぽい...
壊れてないので変更しなくても良さそう
